apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: yml
      labels:
        app: nginx-adoc
        type: server
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3