apiVersion: v1
kind: Service
metadata:
  name: db # este es el nombre de DNS que usaran los pods para acceder al servicio
  labels:
    app: db
spec:
  type: ClusterIP # es el default asi que podriamos borrar esta linea
  ports:
    - name: "db-service"
      port: 5432
      targetPort: 5432
  selector:
    app: db
      