apiVersion: v1
kind: Service
metadata:
  name: result # este es el nombre de DNS que usaran los pods para acceder al servicio
  labels:
    app: result
spec:
  type: NodePort # es el default asi que podriamos borrar esta linea
  ports:
    - name: "result-service"
      port: 8081
      targetPort: 80
      nodePort: 31001
  selector:
    app: result 
      