apiVersion: v1
kind: Service
metadata:
  name: vote # este es el nombre de DNS que usaran los pods para acceder al servicio
  labels:
    app: vote 
spec:
  type: NodePort # es el default asi que podriamos borrar esta linea
  ports:
    - name: "vote-service"
      port: 8080
      targetPort: 80
      nodePort: 31000
  selector:
    app: vote 
      