apiVersion: v1
kind: Service
metadata:
  name: redis # este es el nombre de DNS que usaran los pods para acceder al servicio
  labels:
    app: redis
spec:
  type: ClusterIP # es el default asi que podriamos borrar esta linea
  ports:
    - name: "redis-service"
      port: 6379
      targetPort: 6379
  selector:
    app: redis
      